{{- range .Values.vaultSecrets }}
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: {{ .name }}
spec:
  backendType: vault
  vaultRole: kubernetes-external-secrets
  dataFrom:
    {{- range .dataFrom }}
    - {{ . }}
    {{- end }}
{{- end }}
