{{- range .Values.vaultImagePullSecrets }}
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: {{ .name }}
spec:
  backendType: vault
  vaultRole: kubernetes-external-secrets
  template:
    type: kubernetes.io/dockerconfigjson
  data:
    - key: {{ .key }}
      name: .dockerconfigjson
      property: {{ .propertyName }}
{{- end }}