{{- if .Values.mountFiles -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "backend-app.fullname" . }}
  labels:
    {{- include "backend-app.labels" . | nindent 4 }}
data:
  config.yaml: |-
    {{- toYaml .Values.mountFiles.files | nindent 4 }}
{{- end -}}
