{{- $fullName := include "backend-app.fullname" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "backend-app.fullname" . }}
  labels:
    {{- include "backend-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "backend-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- if .Values.ciRef }}
        ciRef: {{ .Values.ciRef }}
        {{- end }}
        {{- toYaml .Values.podAnnotations | nindent 8 }}
      labels:
        {{- include "backend-app.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "backend-app.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.config }}
          args: ["backend-app", "--config", "/etc/backend-app/config.yaml"]
          {{- end }}
          env:
            {{- toYaml .Values.env | nindent 12 }}
          {{- if .Values.envFromSecretNames }}
          envFrom:
          {{- range .Values.envFromSecretNames }}
            - secretRef:
                name: {{ . }}
          {{- end }}
          {{- end }}
          ports:
            {{- range .Values.service.ports }}
            - name: {{ .name }}
              containerPort: {{ .port }}
              protocol: {{ .protocol | default "TCP" }}
            {{- end }}
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          volumeMounts:
            {{- if .Values.config }}
            - name: config
              mountPath: /etc/backend-app/
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
        {{- if .Values.configFile }}
        - name: config
          configMap:
            name: {{ include "backend-app.fullname" . }}
        {{ end }}
