{{- $fullName := include "application.fullname" . -}}
{{- range $containerIndex, $container := .Values.containers }}
{{- range $fileIndex, $file := $container.files }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullName }}-configmap-files-{{ $containerIndex }}-{{ $fileIndex }}
  labels:
    {{- include "application.labels" . | nindent 4 }}
data:
  {{ regexFind "[^/]+$" $file.path }}: {{ $file.content }}
{{- end -}}
{{- end -}}
