# init containers
{{- range $containerIndex, $container := .Values.initContainers }}
{{- range $fileIndex, $file := $container.files }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "application.fullname" $ }}-configmap-files-init-containers-{{ $containerIndex }}-{{ $fileIndex }}
  labels:
    {{- include "application.labels" $ | nindent 4 }}
data:
  {{ regexFind "[^/]+$" $file.path }}: |- {{ $file.content | nindent 4 }}
{{- end -}}
{{- end -}}

# containers
{{- range $containerIndex, $container := .Values.containers }}
{{- range $fileIndex, $file := $container.files }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "application.fullname" $ }}-configmap-files-containers-{{ $containerIndex }}-{{ $fileIndex }}
  labels:
    {{- include "application.labels" $ | nindent 4 }}
data:
  {{ regexFind "[^/]+$" $file.path }}: |- {{ $file.content | nindent 4 }}
{{- end -}}
{{- end -}}
