---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "application.fullname" . }}
  labels:
    {{- include "application.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range .Values.containers }}
    {{- range .ports }}
    {{- if .exposed }}
    - port: {{ .port }}
      targetPort: {{ .exposedPort | default .port }}
      protocol: {{ .protocol | default "TCP" }}
      name: {{ .exposedName | default .name }}
      {{- if .appProtocol }}
      appProtocol: {{ .appProtocol }}
      {{- end }}
    {{- end }}
    {{- end }}
    {{- end }}
  selector:
    {{- include "application.selectorLabels" . | nindent 4 }}
